server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      #      注册进eureka服务端/注册中心
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com  #eureka服务中心里面注册的服务实例名
    prefer-ip-address: true  #访问路径显示IP地址，即鼠标放到服务实例上去，左下角会显示ip地址+/info

#这里做了ip映射myzuul.com

#修改注册中心服务实例info里面的信息
info:
  app.name: itwang-micorservicecloud
  company.name: com.itwang
  build.artifactId: $project.artifactId$   #自动获取当前项目的项目名
  build.version: $project.version$    #自动获取当前项目的版本号

  #zuul映射访问名
zuul:
#映射访问名
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
#禁掉真实名
#  ignored-services: "*"    #禁掉所有服务真实名
  ignored-services: microservicecloud-dept
#  加映射访问名统一的前缀
  prefix: /itwang        #myzuul.com:9527/itwang/mydept
